FROM fedora:latest

ARG dir
ENV dir=${dir}

ARG shell
ENV shell=${shell}

ARG yes
ENV yes=${yes}

ARG local
ENV local=${local}

RUN dnf install -y sudo curl git

COPY os/docker/entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh

RUN useradd -ms /bin/bash david
RUN echo '%david ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER david
WORKDIR /home/david

COPY --chown=david:david . /tmp/.dotfiles

ENTRYPOINT dir=${dir} shell=${shell} yes=${yes} local=${local} \
    /tmp/entrypoint.sh