#!/usr/bin/env bash

inf "Updating apt and upgrading existing packages"
sudo apt update && sudo apt upgrade -y

if [ $yes -eq 1 ]; then
    touch $HOME/.zshrc # couldn't find a better way to disable zsh wizard on first run
fi

packages=(
    apt-utils
    bash
    zsh
    fish
    git
    curl
    wget
    vim
    neovim
    nano
    tmux
    htop
    # fzf # couldn't get keybindings to work
    bat # batcat bin
    exa
    fd-find # fdfind bin
)

inf "Installing packages $(_g ${packages[@]})"
sudo apt install -y --assume-yes ${packages[@]}

inf "Installing $(_g fzf)"
if [ -d "$HOME/.fzf" ]; then
    warn "$(_y fzf) already installed"
    return
fi
git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
yes | $HOME/.fzf/install

inf "Installing $(_g go)"
if [[ $arch == "aarch64" ]]; then
    gotar="go1.19.4.linux-arm64.tar.gz"
else
    gotar="go1.19.4.linux-amd64.tar.gz"
fi
wget "https://go.dev/dl/$gotar" -O /tmp/$gotar
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf /tmp/$gotar
rm -f /tmp/$gotar

symlink $HOME/.bashrc $dir/ubuntu/config/.bashrc
symlink $HOME/.zshrc $dir/ubuntu/config/.zshrc

if ! grep -q $shell /etc/shells; then
    err "$(_r $shell) is not a valid shell"
    exit 1
fi

inf "Setting $(_g $(which $shell)) as default shell"
sudo chsh -s $(which $shell) $(whoami)
